# Generated by Django 3.2.11 on 2026-03-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(max_length=12),
        ),
    ]
