# Generated by Django 6.0.3 on 2026-03-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_registration_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='bloodgroup',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
