# Generated by Django 6.0.3 on 2026-03-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_registration_age_alter_registration_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
