# Generated by Django 6.0.3 on 2026-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
