# Generated by Django 6.0.3 on 2026-03-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_doctor_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='fee',
            new_name='fees',
        ),
    ]
