# Generated by Django 6.0.3 on 2026-04-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
